### ISSUE TITLE
create new demo record for data set

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-demosite#20]
In order to test new data visualisation tools, it would be good to create a new demo record with attached zip files containing public data sets.  This record could then be used in various test cases related to data previewing and visualising.

For example, one could take world population figures from http://en.wikipedia.org/wiki/World_population

P.S. The new record could be part of an existing collection, like Reports, or we can create a new collection called "Data".

**Comment by jirikuncar** [comment]
The demo record has been moved to: invenio_records/data/marc21/bibliographic.xml

**Comment by tiborsimko** [comment]
... and the demo record had been integrated here: https://github.com/inveniosoftware/invenio/pull/2208
