### ISSUE TITLE
tests: failing regressions testsuite

### ISSUE THREAD

**Issue by bogdan-kulynych** [inveniosoftware/invenio-demosite#29]
```
Ran 1095 tests in 499.200s

FAILED (failures=32, errors=684, skipped=115)
```

(from [travis](https://s3.amazonaws.com/archive.travis-ci.org/jobs/29836777/log.txt))

**Comment by jirikuncar** [comment]
I would go with following strategy:

1. Disable regression tests;
2. Enable `inveniomanage demosite populate` and make sure it's working well;
3. Enable and fix **non**-HTML dependent regression tests.

**Comment by jirikuncar** [comment]
We have shifted our focus towards Invenio 3.
