### ISSUE TITLE
collections: portalbox text overflow

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-demosite#38]
Hi guys,
I installed the demo site and in home page, in right bar, the text doesn't respect the width of the box.
This css seems to fix the issue:

.panel-body {
    word-wrap: break-word;
}

I don't understand where the system save the css. So I publish the fix here. :)
Leo

Before:
![before](https://cloud.githubusercontent.com/assets/377047/4134538/9b1a811a-336d-11e4-9917-44ecf13984fc.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/377047/4134533/8ca52072-336d-11e4-9b53-f77d1ba56135.jpg)

**Comment by jirikuncar** [comment]
@hachreak this should be fixed in upstream Invenio somewhere in `search` (or `collections` in v2.1) modules.

**Comment by jirikuncar** [comment]
@hachreak can you close this one and re-open in Invenio? Thanks

**Comment by hachreak** [comment]
done
